package frontend;

import DB.DBConnection;
import java.sql.Connection;

public class HolidayDeclare extends javax.swing.JFrame {

    int selectedId = -1;

    /**
     * Creates new form HolidayDeclare
     */
    public HolidayDeclare() {
        initComponents();
        loadHolidayTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(51, 82, 241));
        setPreferredSize(new java.awt.Dimension(800, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 82, 241));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Holiday Reason", "Holiday Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 120, 630, 420);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Holiday Declaration");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 10, 176, 28);

        jButton1.setText("View Holiday List");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);
        jButton1.setBounds(312, 80, 140, 30);

        jButton2.setText("Back");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2);
        jButton2.setBounds(560, 80, 110, 30);

        jButton3.setText("Add Holiday");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel1.add(jButton3);
        jButton3.setBounds(80, 80, 110, 30);

        jButton4.setText("update ");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel1.add(jButton4);
        jButton4.setBounds(220, 80, 80, 30);

        jButton5.setText("Delete");
        jButton5.addActionListener(this::jButton5ActionPerformed);
        jPanel1.add(jButton5);
        jButton5.setBounds(462, 80, 80, 30);

        jButton6.setText("Print");
        jButton6.addActionListener(this::jButton6ActionPerformed);
        jPanel1.add(jButton6);
        jButton6.setBounds(640, 580, 72, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 800);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AdminDashboard admindb = new AdminDashboard();
        admindb.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AddHoliday hd = new AddHoliday();
        hd.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DBConnection.conn;

            String query = "SELECT * FROM holidays";
            java.sql.PreparedStatement ps = con.prepareStatement(query);
            java.sql.ResultSet rs = ps.executeQuery();

            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) jTable1.getModel();

            // Clear existing rows
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("event"),
                    rs.getDate("holiday_date")
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();

        if (row != -1) {
            selectedId = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();

        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a row first");
            return;
        }

        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) jTable1.getModel();

        int id = Integer.parseInt(model.getValueAt(row, 0).toString());
        String event = model.getValueAt(row, 1).toString();
        String date = model.getValueAt(row, 2).toString();

        String newEvent = javax.swing.JOptionPane.showInputDialog(this, "Edit Event", event);
        String newDate = javax.swing.JOptionPane.showInputDialog(this, "Edit Date (YYYY-MM-DD)", date);

        if (newEvent != null && newDate != null) {
            updateHoliday(id, newEvent, newDate);
            loadHolidayTable();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();

        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a row first");
            return;
        }

        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete?",
                "Confirm Delete",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                Connection con = DBConnection.conn;

                String query = "DELETE FROM holidays WHERE id=?";
                java.sql.PreparedStatement ps = con.prepareStatement(query);
                ps.setInt(1, id);

                ps.executeUpdate();

                javax.swing.JOptionPane.showMessageDialog(this, "Deleted Successfully");

                loadHolidayTable();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            java.text.MessageFormat header = new java.text.MessageFormat("Holiday List");
            java.text.MessageFormat footer = new java.text.MessageFormat("Page {0}");

            boolean complete = jTable1.print(
                    javax.swing.JTable.PrintMode.FIT_WIDTH,
                    header,
                    footer
            );

            if (complete) {
                javax.swing.JOptionPane.showMessageDialog(this, "Printing Complete");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Printing Cancelled");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void loadHolidayTable() {
        try {
            java.sql.Connection con = DBConnection.conn;

            String query = "SELECT * FROM holidays";
            java.sql.PreparedStatement ps = con.prepareStatement(query);
            java.sql.ResultSet rs = ps.executeQuery();

            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) jTable1.getModel();

            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("event"),
                    rs.getDate("holiday_date")
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void updateHoliday(int id, String event, String date) {
        try {
            Connection con = DBConnection.conn;

            String query = "UPDATE holidays SET event=?, holiday_date=? WHERE id=?";
            java.sql.PreparedStatement ps = con.prepareStatement(query);

            ps.setString(1, event);
            ps.setString(2, date);
            ps.setInt(3, id);

            ps.executeUpdate();

            javax.swing.JOptionPane.showMessageDialog(this, "Updated Successfully");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
