/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class RecordAttendance extends javax.swing.JFrame {

    /**
     * Creates new form RecordAttendance
     */
    public RecordAttendance() {
        initComponents();
        setTodayDate();
        setTableEditable();
        loadStaff();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 82, 241));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 800));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Staff Name", "Attendance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 160, 550, 402);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Staff Attendence");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(320, 10, 176, 28);

        jButton1.setText("View Attendence");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);
        jButton1.setBounds(280, 90, 140, 30);

        jButton2.setText("Back");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2);
        jButton2.setBounds(570, 90, 99, 30);

        jButton3.setText("Add Attendence");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel1.add(jButton3);
        jButton3.setBounds(120, 90, 140, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 10, 40, 30);
        jPanel1.add(date);
        date.setBounds(70, 10, 130, 30);

        jButton4.setText("Update");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel1.add(jButton4);
        jButton4.setBounds(445, 93, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ClerkDashboard().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try {
        java.sql.Connection con = DB.DBConnection.conn;

        String todayDate = date.getText();

        // CHECK HOLIDAY
        String checkHoliday = "SELECT * FROM holidays WHERE holiday_date=?";
        java.sql.PreparedStatement psCheck = con.prepareStatement(checkHoliday);
        psCheck.setString(1, todayDate);

        java.sql.ResultSet rsCheck = psCheck.executeQuery();

        if (rsCheck.next()) {
            javax.swing.JOptionPane.showMessageDialog(this, "❌ Today is a Holiday! Attendance not allowed.");
            return; // STOP execution
        }

        //SAVE ATTENDANCE
        String query = "INSERT INTO attendance (staff_id, attendance_date, status) VALUES (?, ?, ?) "
                + "ON DUPLICATE KEY UPDATE status=?";

        java.sql.PreparedStatement ps = con.prepareStatement(query);

        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) jTable1.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {

            int staffId = Integer.parseInt(model.getValueAt(i, 0).toString());
            boolean status = (Boolean) model.getValueAt(i, 2);

            ps.setInt(1, staffId);
            ps.setString(2, todayDate);
            ps.setBoolean(3, status);
            ps.setBoolean(4, status);

            ps.executeUpdate();
        }

        javax.swing.JOptionPane.showMessageDialog(this, "✅ Attendance Saved Successfully");

        jButton1ActionPerformed(null);

    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {                                         
            // TODO add your handling code here:
            // Check holiday before loading
            String checkHoliday = "SELECT * FROM holidays WHERE holiday_date=?";
            PreparedStatement psCheck = DB.DBConnection.conn.prepareStatement(checkHoliday);
            try {
                psCheck.setString(1, date.getText());
            } catch (SQLException ex) {
                System.getLogger(RecordAttendance.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            
            ResultSet rsCheck = null;
            try {
                rsCheck = psCheck.executeQuery();
            } catch (SQLException ex) {
                System.getLogger(RecordAttendance.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            
            if (rsCheck.next()) {
                JOptionPane.showMessageDialog(this, "🎉 Today is Holiday: " + rsCheck.getString("event"));
                return;
            }
            // VIEW ATTENDANCE
            try {
                java.sql.Connection con = DB.DBConnection.conn;
                
                String query = "SELECT s.id, s.name, a.status "
                        + "FROM staff s LEFT JOIN attendance a "
                        + "ON s.id = a.staff_id AND a.attendance_date=?";
                
                java.sql.PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, date.getText());
                
                java.sql.ResultSet rs = ps.executeQuery();
                
                javax.swing.table.DefaultTableModel model
                        = (javax.swing.table.DefaultTableModel) jTable1.getModel();
                
                model.setRowCount(0);
                
                while (rs.next()) {
                    
                    Boolean status = rs.getObject("status") != null
                            ? rs.getBoolean("status")
                            : false;
                    
                    model.addRow(new Object[]{
                        rs.getInt("id"),
                        rs.getString("name"),
                        status
                    });
                }
                
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (SQLException ex) {
            System.getLogger(RecordAttendance.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // UPDATE = SAME AS SAVE
        jButton3ActionPerformed(evt);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void setTodayDate() {
        java.time.LocalDate today = java.time.LocalDate.now();
        date.setText(today.toString()); // yyyy-MM-dd
    }

    private void loadStaff() {
        try {
            java.sql.Connection con = DB.DBConnection.conn;

            String query = "SELECT id, name FROM staff";
            java.sql.PreparedStatement ps = con.prepareStatement(query);
            java.sql.ResultSet rs = ps.executeQuery();

            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) jTable1.getModel();

            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("name"),
                    false
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setTableEditable() {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Staff ID", "Staff Name", "Attendance"
                }
        ) {
            Class[] types = new Class[]{
                Integer.class, String.class, Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int row, int column) {
                return column == 2; // only checkbox editable
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
